### ISSUE TITLE
nokogiri ?

### ISSUE THREAD

**Issue by CanadianJeff** [rogerbraun/StalkerChan#1]
```
# ruby stalkerchan.rb --help
/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- nokogiri (LoadError)
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
        from stalkerchan.rb:4
```

**Comment by CanadianJeff** [comment]
```
# gem install exifr
Fetching: exifr-1.2.5.gem (100%)
Successfully installed exifr-1.2.5
1 gem installed
Installing ri documentation for exifr-1.2.5...
Installing RDoc documentation for exifr-1.2.5...
# gem install hpricot
Building native extensions.  This could take a while...
Successfully installed hpricot-0.8.6
1 gem installed
Installing ri documentation for hpricot-0.8.6...
Installing RDoc documentation for hpricot-0.8.6...
# gem install nokogiri
Fetching: mini_portile2-2.1.0.gem (100%)
ERROR:  Error installing nokogiri:
        mini_portile2 requires Ruby version >= 1.9.2.
```
